# Generated by scripts/bump_homebrew_formula.sh — do not edit by hand.
#
# The URLs below point at official AirCode release assets.
class Aircode < Formula
  desc "Blazing-fast TUI coding agent — multi-model, swarm coordination, 30+ tools"
  homepage "https://github.com/jettysoft/aircode-releases"
  version "0.55.45"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.45/aircode-macos-aarch64.tar.gz"
      sha256 "9a6240f0912a9154356af796f3e2d303c8a25b603d8067b3ecc5cca6694e6a2d"

      def install
        bin.install "aircode-macos-aarch64" => "aircode"
      end
    end

    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.45/aircode-macos-x86_64.tar.gz"
      sha256 "ff095c92e748e785d60fbfb8aab1c7174ed90ba3278452f7f7c0c5992376406c"

      def install
        bin.install "aircode-macos-x86_64" => "aircode"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.45/aircode-linux-x86_64.tar.gz"
      sha256 "e75ed632aebc9162eaf2b95993e41ef7ac355bc201a3bd17a36739182d92d739"

      def install
        libexec.install "aircode-linux-x86_64", "aircode-linux-x86_64.bin"
        libexec.install Dir["libssl.so*", "libcrypto.so*"]
        bin.install_symlink libexec/"aircode-linux-x86_64" => "aircode"
      end
    end

  end

  test do
    assert_match "aircode", shell_output("#{bin}/aircode --version")
  end
end
