# Generated by scripts/bump_homebrew_formula.sh — do not edit by hand.
#
# The URLs below point at official AirCode release assets.
class Aircode < Formula
  desc "Blazing-fast TUI coding agent — multi-model, swarm coordination, 30+ tools"
  homepage "https://github.com/jettysoft/aircode-releases"
  version "0.55.38"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.38/aircode-macos-aarch64.tar.gz"
      sha256 "b9618409110852abb80783bf7334d8b77bea80d4d5fb09dad24be93ed0365176"

      def install
        bin.install "aircode-macos-aarch64" => "aircode"
      end
    end

    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.38/aircode-macos-x86_64.tar.gz"
      sha256 "113d09ef582e3c5c20a3fbcf48b35f71336415c04728cab0a3cc636f36046542"

      def install
        bin.install "aircode-macos-x86_64" => "aircode"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.38/aircode-linux-x86_64.tar.gz"
      sha256 "f2712234ce2d269b800cb9e65bde8d9dcb0f4a295ca004ad0075629a1016f2e7"

      def install
        libexec.install "aircode-linux-x86_64", "aircode-linux-x86_64.bin"
        libexec.install Dir["libssl.so*", "libcrypto.so*"]
        bin.install_symlink libexec/"aircode-linux-x86_64" => "aircode"
      end
    end

  end

  test do
    assert_match "aircode", shell_output("#{bin}/aircode --version")
  end
end
