# Generated by scripts/bump_homebrew_formula.sh — do not edit by hand.
#
# The URLs below point at official AirCode release assets.
class Aircode < Formula
  desc "Blazing-fast TUI coding agent — multi-model, swarm coordination, 30+ tools"
  homepage "https://github.com/jettysoft/aircode-releases"
  version "0.55.43"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.43/aircode-macos-aarch64.tar.gz"
      sha256 "b59cac1ed7d3aaffc54ac6669a6fb30765cfea23e5de39ba3e8f3754c2d92851"

      def install
        bin.install "aircode-macos-aarch64" => "aircode"
      end
    end

    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.43/aircode-macos-x86_64.tar.gz"
      sha256 "cb1ba246f1b52f0508c806d28841a37076f634e789ee62d5003313504be6958b"

      def install
        bin.install "aircode-macos-x86_64" => "aircode"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jettysoft/aircode-releases/releases/download/v0.55.43/aircode-linux-x86_64.tar.gz"
      sha256 "7eb52477a1d2b30a5c8888dcb49324bd00ba1580d3ac906c916d9edc222d4bed"

      def install
        libexec.install "aircode-linux-x86_64", "aircode-linux-x86_64.bin"
        libexec.install Dir["libssl.so*", "libcrypto.so*"]
        bin.install_symlink libexec/"aircode-linux-x86_64" => "aircode"
      end
    end

  end

  test do
    assert_match "aircode", shell_output("#{bin}/aircode --version")
  end
end
